[supervisord]
nodaemon=true

[program:obs]
command=/usr/bin/obs --safe-mode --verbose --disable-shutdown-check
environment=DISPLAY=":1",LIBGL_ALWAYS_SOFTWARE="1"
autostart=false
autorestart=false
stdout_logfile=/var/log/obs.log
stderr_logfile=/var/log/obs-error.log
