[supervisord]
nodaemon=true

[program:obs]
command=/usr/bin/obs --startrecording
environment=DISPLAY=":1"
autostart=true
autorestart=true
stdout_logfile=/var/log/obs.log
stderr_logfile=/var/log/obs-error.log
